### PR TITLE
deps: controller-runtime v0.7.0, go 1.15, other deps to >v1 paths

### PR DESCRIPTION
**Pull request by estroz**
This commit updates dependencies

- deps: bump controller-runtime to v0.7.0 and other deps to their >v1 module path, and go to version 1.15
- pkg/patterns: update >v1 module paths

### CODE REVIEW

**Comment by atoato88** [comment]
/lgtm
Thank you to update :tada:

**Comment by christopherhein** [comment]
/lgtm

Hopefully, we can get this merged soon, not that it's breaking just to align all kb projects on the same CR version.

**Pull request merged**
