### PR TITLE
Optimization: Reuse HTTPClient / DynamicClient in reconcile

### PR DESCRIPTION
**Pull request by justinsb**
Should be slightly more efficient via better HTTP connection reuse.

### CODE REVIEW

**Comment by justinsb** [comment]
cc @cheftako  - as requested re reusing the DynamicClient; I think the answer is that the caller should try to provide a cached DynamicClient, because client-go is more efficient if we can reuse the `http.Client`.  Added a comment and ensured that k-d-p itself passes the dynamic client (which we actually already have!)

**Comment by atoato88** [comment]
I am not sure about my comment is related with this PR. :thinking: 

Current direct applier uses the `dynamicClient` at [here](https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/blob/8e6cf52b8fdd8dc1bb1516529c994ccb46cd9ab7/pkg/patterns/declarative/pkg/applier/direct.go#L92).
This always uses the dynamicClient from Factory.
Should we update the `direct.go` to use the `opt.DynamicClient`?

On the other hand, [`dynamicClient` in `applylib.go`](https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/blob/8e6cf52b8fdd8dc1bb1516529c994ccb46cd9ab7/pkg/patterns/declarative/pkg/applier/applylib.go#L58-L65) takes care of the existance of `opt.DynamicClient`.
It's OK as-is, I think.

**Comment by justinsb** [comment]
Great point @atoato88, and you're absolutely right.  I added a commit that should also reuse the dynamic-client in the direct applier.

(I don't think we can practically reuse it in the exec applier.)

I also noticed that we probably should be trying to reuse the http client [here](https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/blob/8e6cf52b8fdd8dc1bb1516529c994ccb46cd9ab7/pkg/patterns/declarative/watch.go#L114), but I think I'll have to send a separate PR for that one!

**Comment by atoato88** [comment]
@justinsb 
Thank you for the response and update.

> (I don't think we can practically reuse it in the exec applier.)

I think so too.

> I also noticed that we probably should be trying to reuse the http client [here](https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/blob/8e6cf52b8fdd8dc1bb1516529c994ccb46cd9ab7/pkg/patterns/declarative/watch.go#L114), but I think I'll have to send a separate PR for that one!

OK!
We can go forward. :rocket:

**Pull request merged**
