### PR TITLE
Bump k8s.io/kubectl to 0.29.1

### PR DESCRIPTION
**Pull request by tomasaschan**
Main motivation is to include https://github.com/kubernetes/kubernetes/pull/122346

I don't know if there's a way to do this that touches fewer dependencies; I tried a bunch of ways with `go get [-u] k8s.io/kubectl[@0.29.1]` but all of them resulted in this full set of changes.

### CODE REVIEW

**Comment by tomasaschan** [comment]
@justinsb This is currently blocking us from bumping `k8s.io/kubectl` to 0.29.1 and get [this fix](https://github.com/kubernetes/kubernetes/pull/122346). Any chance you can review this soon-ish? :)

**Comment by atoato88** [comment]
/assign @justinsb 
Could you review this?

**Comment by atoato88** [comment]
@justinsb 
Gentle ping, cloud you review this?

**Comment by atoato88** [comment]
@tomasaschan @justinsb 
Can we close this PR w/o merging, because #380 is merged?
That PR had the update bumping kubectl to v0.29.1.

**Pull request closed without merging**
