### PR TITLE
deps: bump controller runtime to 0.8.0

### PR DESCRIPTION
**Pull request by varshaprasad96**
deps: bump controller runtime to 0.8.0

### CODE REVIEW

**Comment by atoato88** [comment]
/lgtm
Thank you to create this! :smile:

**Review by camilamacedo86 — APPROVED** [review]
/approve

**Comment by Liujingfang1** [comment]
/lgtm

@justinsb Could you also take a look?

**Comment by varshaprasad96** [comment]
@justinsb could you please take a look at this PR. This is required for https://github.com/kubernetes-sigs/kubebuilder/pull/1961

**Comment by justinsb** [comment]
Sorry for delay and thanks for the PR!

/approve
/lgtm

**Pull request merged**
