### PR TITLE
Add template for issue and PR

### PR DESCRIPTION
**Pull request by atoato88**
This PR add template files for issue and PR on GitHub.
It's good to clarify information about issue and PR.

I referred k/k's templates for issue and PR.
But that is too much input items for this repository I think, I cut some items from it for ease to input.

### CODE REVIEW

**Comment by justinsb** [comment]
It's probably a lot of information for a library (vs something directly user facing), but I :heart: the idea and we can always trim it down later if we need to!

/approve
/lgtm

**Comment by justinsb** [comment]
/retest

Test failure was unrelated, should have been fixed by #155

**Comment by atoato88** [comment]
@justinsb 
Thank you for approving.


> ... we can always trim it down later if we need to!

Yes, I agree with your idea. We can always fit the template to our usecase.

**Pull request merged**
