### PR TITLE
owners: add tomasaschan to reviewers

### PR DESCRIPTION
**Pull request by justinsb**

### CODE REVIEW

**Comment by justinsb** [comment]
/hold for input from tomasaschan 

@tomasaschan would like to be a reviewer? (With a view to getting ownership in time, but we're not supposed to start you as an owner)  I think you have demonstrated a deep understanding of the code and an ability to contribute.

cc @atoato88 and @johnsonj  - do you agree with this suggestion?

**Comment by tomasaschan** [comment]
I'd be happy to!

**Comment by tomasaschan** [comment]
/lgtm

Just to formally indicate this (even though it won't work until this is merged, IIUC).

**Comment by justinsb** [comment]
> changing LGTM is restricted to collaborators

Well that's not good, either prow is having a moment or maybe we've change the config (so that approvers can't LGTM?)... I'll try to figure out what's going on here

**Comment by atoato88** [comment]
[k8s-ci-bot said](https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/pull/381#issuecomment-2002211468):
> User is not a member of the org. Satisfy at least one of these conditions to make the user trusted.

@tomasaschan is not member of org member?
Could you reat the document [here](https://github.com/kubernetes/community/blob/master/community-membership.md#member) for becoming the member of that.

**Comment by tomasaschan** [comment]
Hum. I think I have everything in place except two sponsors from different companies. @atoato88 @justinsb OK if I name the two of you as my sponsors? (I can't tell from your GH profile if you're also a Googler, @atoato88 ...)

**Comment by tomasaschan** [comment]
https://github.com/kubernetes/org/issues/4837

**Comment by atoato88** [comment]
I can become your sponsor!
I know your activities on this repo and I am not a googler. :smile:

**Comment by atoato88** [comment]
Thank you for mentioning me, I commented on https://github.com/kubernetes/org/issues/4837

**Comment by tomasaschan** [comment]
Thank you! Then I think we just need a +1 from Justin there too, which I suppose will have to wait until I after kubecon :)

**Comment by tomasaschan** [comment]
I've now been added as a member of the org, so this should be unblocked!

/hold cancel

(probably won't work)

**Comment by atoato88** [comment]
Thank you for catching up this PR and I'm very apreciate that you joined our repo! :smile:

**Pull request merged**
