### PR TITLE
Simplify List flattening logic

### PR DESCRIPTION
**Pull request by justinsb**
Refactor to ensure that we build and flatten the objects in one place,
simplifying execution.  The intermediate call to VersionCheck (should)
prefer flattened objects.

### CODE REVIEW

**Comment by atoato88** [comment]
It looks that updating the test case is needed from [this result](https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kubebuilder-declarative-pattern/316/pull-declarative-test/1632952839514886144#1:build-log.txt%3A608-699).

Is it caused by updating target object with flatten one?

**Comment by atoato88** [comment]
The test result seems flaky one? :thinking:

**Review by yuwenma — APPROVED** [review]

**Pull request merged**
