### PR TITLE
Make atoato88 an approver

### PR DESCRIPTION
**Pull request by justinsb**
atoato88 has demonstrated deep understanding of the code, and has a
track record of participation.  Thank you atoato88!

### CODE REVIEW

**Comment by justinsb** [comment]
@atoato88 would you like to become an approver for the project?  You have a long track record here that justifies it IMO.

/assign johnsonj for approval

/hold for atoato88 to accept

**Comment by atoato88** [comment]
I'm so appreciate.
Yes please😄 

Besides here, I would like to continue reviewing cluster-addons also. 😉

**Comment by stealthybox** [comment]
> You have a long track record here

+1

Thanks for your efforts here @atoato88

**Comment by justinsb** [comment]
Looks like consensus - thank you all and @atoato88 :-)

/hold cancel

**Pull request merged**
