### PR TITLE
Fix to get the correct dns domain

### PR DESCRIPTION
**Pull request by rajansandeep**

### CODE REVIEW

**Comment by rajansandeep** [comment]
This PR will fix the failing test in https://github.com/kubernetes-sigs/cluster-addons/pull/98

**Comment by atoato88** [comment]
Thank you to create this :smile: 
I think this PR fixes bug.
Could you add unit-test for this PR code-set?
It's good for clear review and approve.

**Comment by justinsb** [comment]
A dedicated unit test would be great, but we can do that in a follow-on PR.  There's currently a (failing) unit test in the downstream cluster-addons project :-)

/approve
/lgtm

**Pull request merged**
