### PR TITLE
Checks for ignore reconciliation annotations

### PR DESCRIPTION
**Pull request by SomtochiAma**

### CODE REVIEW

**Comment by justinsb** [comment]
We discussed in pairing; we agreed we should look for the annotation on the objects in the cluster, by reading them before applying.  (And that same logic is useful in the health check, I believe)

**Comment by atoato88** [comment]
This PR relates to #111 ?
If so, this PR is replaced with it and will close w/o merge?

**Comment by SomtochiAma** [comment]
> This PR relates to #111 ?
> If so, this PR is replaced with it and will close w/o merge?

This PR could still be important. It checks for the ignore annotation on the Custom resource

**Comment by SomtochiAma** [comment]
@justinsb should I close this?

**Comment by atoato88** [comment]
@SomtochiAma 
Sorry for late response.
> It checks for the ignore annotation on the Custom resource

Yes, I think so too, current code of PR is LGTM.

/lgtm

**Comment by justinsb** [comment]
@SomtochiAma and I discussed this; this might be useful in future so we don't just want to close it, but we instead implemented first an annotation on the manifest itself.

/ok-to-test

/hold

**Pull request closed without merging**
