### PR TITLE
Add license notice to each files

### PR DESCRIPTION
**Pull request by atoato88**
There are no license notice at top of each files.
This PR adds license notice to each files.

Fixes: #15

### CODE REVIEW

**Comment by atoato88** [comment]
/assign @justinsb

I’m not sure assigning you is correct..

**Comment by justinsb** [comment]
Thanks and sorry about the conflict @atoato88  - needs a rebase.

We should (separately) add a script to verify our boilerplate - there's a canonical script in https://github.com/kubernetes/repo-infra .. maybe I'll tackle that :-)

**Comment by justinsb** [comment]
/approve
/lgtm

(but won't do you much good without a rebase)

**Comment by atoato88** [comment]
rebase is finished. @justinsb

**Comment by justinsb** [comment]
Thanks @atoato88 !

/approve
/lgtm

**Pull request merged**
