### PR TITLE
deps: bump k8s to v1.20

### PR DESCRIPTION
**Pull request by estroz**
Follows up on #139.

### CODE REVIEW

**Comment by estroz** [comment]
@atoato88 can you review/approve this again?

**Comment by atoato88** [comment]
/lgtm
@estroz 
Thank you to update & mention to me.

**Comment by estroz** [comment]
@atoato88 np! Can you `/approve` this as well, or are you waiting for another to approve? If so, I can assign someone else.

**Comment by atoato88** [comment]
Thank you to quick response. :smile: 
Should I become approver in this repo.. :thinking:

**Comment by estroz** [comment]
Closing in favor of #146 

/close

**Pull request closed without merging**
