### PR TITLE
WIP: mockkubeapiserver: some schema awareness

### PR DESCRIPTION
**Pull request by justinsb**
Enough to support patch/merge a little better.

### CODE REVIEW

**Comment by apelisse** [comment]
[APIServer/fieldmanager](https://github.com/kubernetes/kubernetes/tree/master/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/fieldmanager) contains the code that uses [smd](https://github.com/kubernetes-sigs/structured-merge-diff/) in Kubernetes.

You need a [Parser](https://github.com/kubernetes-sigs/structured-merge-diff/blob/master/typed/parser.go#L52-L63) in order to [parse YAML objects](https://github.com/kubernetes-sigs/structured-merge-diff/blob/master/typed/parser.go#L94-L103) into something that you can [Apply](https://github.com/kubernetes-sigs/structured-merge-diff/blob/master/merge/update.go#L162) or [Update](https://github.com/kubernetes-sigs/structured-merge-diff/blob/master/merge/update.go#L123). It's done by instantiating a [`FieldManager`](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/endpoints/handlers/fieldmanager/fieldmanager.go#L87-L95), but this requires a bunch of version convertor, defaulter and creator that you can probably fake.

**Comment by justinsb** [comment]
Thanks - I started to give that a go in https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/pull/270 .. it looks pretty good!

**Comment by justinsb** [comment]
Marking as WIP in favor of the approach in #270

**Comment by justinsb** [comment]
Merged the approach in #270 instead - thanks @apelisse  :-)

/close

**Pull request closed without merging**
