### PR TITLE
owners: promote tomasaschan to owner

### PR DESCRIPTION
**Pull request by tomasaschan**
This was discussed already when adding me to reviewers in #381 but hasn't happened yet.

### CODE REVIEW

**Comment by atoato88** [comment]
/lgtm
@tomasaschan has deep knowledge and many activities of this repo.

**Comment by atoato88** [comment]
@justinsb 
Could you check this?

**Comment by justinsb** [comment]
Agreed - thank you @tomasaschan and @atoato88 

/approve
/lgtm

**Pull request merged**
