### PR TITLE
Chore/bump k8s 1.24

### PR DESCRIPTION
**Pull request by everettraven**
Draft PR for testing k8s 1.24 bump changes

### CODE REVIEW

**Comment by camilamacedo86** [comment]
Hi @everettraven, 

Could this one be PR now and no longer a draft so that we can move forward?

**Comment by camilamacedo86** [comment]
Also, can we update the title like we do for kubebuilder ⚠️ upgrade from 1.23 to 1.24

**Comment by everettraven** [comment]
@camilamacedo86 I provided the information that I had found to @NikhilSharmaWe  and @NikhilSharmaWe has been updating their PR to get it working. I figured it would be nice allow @NikhilSharmaWe to update their PR and get that one merged instead since they had already done work on it and I just helped out a bit :)

**Comment by everettraven** [comment]
However if @NikhilSharmaWe would prefer that we go ahead and move along with this one as opposed to #217 then I would be happy to convert this to a regular PR and adjust the title

**Comment by camilamacedo86** [comment]
closing this one in favor of https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/pull/217

**Pull request closed without merging**
