### PR TITLE
[Trival] replace beta label to GA label for kubernetes

### PR DESCRIPTION
**Pull request by wawa0210**
/kind cleanup

Ref: kubernetes/kubernetes#89477

/assign @pwittrock

### CODE REVIEW

**Comment by wawa0210** [comment]
@ justinsb @ johnsonj @ atoato88 

Can you take the time to help review this pr, thank you very much

**Comment by atoato88** [comment]
@wawa0210 
Thank you for notification.
/lgtm

**Comment by johnsonj** [comment]
/approved

thank you @wawa0210

**Comment by atoato88** [comment]
I checked [log](https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_kubebuilder-declarative-pattern/77/pull-declarative-test/1247918081976569857) and merge conflict is occured.

@wawa0210 
This PR needs rebase.
But, there are not files changed by this PR because that #81 is merged.
#81 removed `examples/dashboard-operator` folder itself.

@johnsonj 
What should we do?
Close this PR without merge?

**Comment by johnsonj** [comment]
@atoato88 I think this change should now be made in kubernetes-sigs/cluster-addons. We should close this PR as it's now obsolete for this repo. 

/close

**Pull request closed without merging**
