### PR TITLE
Use latest version for tests

### PR DESCRIPTION
**Pull request by rajansandeep**
Try and always use the latest build of `kubebuilder-declarative-pattern` for tests in the example operator

### CODE REVIEW

**Comment by rajansandeep** [comment]
`pull-declarative-test` is expected to fail. 
The failing test is fixed in #122 and #123

**Comment by atoato88** [comment]
/assign @justinsb 
Could you review this and other [related PRs in this comment](https://github.com/kubernetes-sigs/kubebuilder-declarative-pattern/pull/125#issuecomment-708091648) ?

**Comment by justinsb** [comment]
/retest

#122 and #123 are now merged so :crossed_fingers:

**Comment by justinsb** [comment]
Tests are green :tada: 

Thanks for doing this @rajansandeep 

/approve
/lgtm

**Pull request merged**
