### PR TITLE
Fix incorrect path for Kustomize in addon operators

### PR DESCRIPTION
**Pull request by rajansandeep**
Kustomize cannot find the `kustomization.yaml` file for creating the final manifest.

The error before this fix:
```
2020-04-17T13:13:20.045-0400	ERROR	running kustomize to create final manifest	{"error": "unable to find one of 'kustomization.yaml', 'kustomization.yml' or 'Kustomization' in directory '/'"}
github.com/go-logr/zapr.(*zapLogger).Error
	/Users/srajan/go/pkg/mod/github.com/go-logr/zapr@v0.1.0/zapr.go:128
sigs.k8s.io/kubebuilder-declarative-pattern/pkg/patterns/declarative.(*Reconciler).reconcileExists
	/Users/srajan/go/pkg/mod/sigs.k8s.io/kubebuilder-declarative-pattern@v0.0.0-20200415210853-85eb326a6add/pkg/patterns/declarative/reconciler.go:145
sigs.k8s.io/kubebuilder-declarative-pattern/pkg/patterns/declarative.(*Reconciler).Reconcile
	/Users/srajan/go/pkg/mod/sigs.k8s.io/kubebuilder-declarative-pattern@v0.0.0-20200415210853-85eb326a6add/pkg/patterns/declarative/reconciler.go:106
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/Users/srajan/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:256
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/Users/srajan/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:232
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	/Users/srajan/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:211
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1
	/Users/srajan/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:152
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/Users/srajan/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:153
k8s.io/apimachinery/pkg/util/wait.Until
	/Users/srajan/go/pkg/mod/k8s.io/apimachinery@v0.17.2/pkg/util/wait/wait.go:88
2020-04-17T13:13:20.251-0400	ERROR	controller-runtime.controller	Reconciler error	{"controller": "coredns-controller", "request": "kube-system/coredns-operator", "error": "error running kustomize: unable to find one of 'kustomization.yaml', 'kustomization.yml' or 'Kustomization' in directory '/'"}
```

This PR fixes the error and also updates the test to reflect the case where an operator uses Kustomize

Probable related issue: #56

### CODE REVIEW

**Comment by atoato88** [comment]
@rajansandeep 
Thank you to create PR! :tada: 

This PR changes public "Reconciler.**options**" with private "Reconciler.**Options**", I know the reason do that.
"reconcilerParams.kustomize" is also same.

But, we should minimize a range which can access to variable, I think.
It may need some refactorings in Reconciler functions.
Could you do that?

@justinsb 
WDYT?

**Comment by johnsonj** [comment]
Thank you @rajansandeep !

I think @atoato88 's feedback was addressed by the getter. I think this is a good approach. Please raise if that didn't solve it.

/lgtm
/approved

**Pull request merged**
