### PR TITLE
Add support for dashboard v2.0.0 on dashboard-operator

### PR DESCRIPTION
**Pull request by atoato88**
This PR adds support for dashboard v2.0.0 on dashboard-operator.

As of now, latest version is v2.0.0-rc3, so I add dashboard  v2.0.0-rc3 as `develop` channel.

### CODE REVIEW

**Comment by shu-mutou** [comment]
FYI: rc5 was released last night.

**Comment by johnsonj** [comment]
Thanks @atoato88 - Is this still WIP? Overall it looks good to me. Adding this as a develop channel is great to see!

also sorry for the delay! i've been on vacation.

/approve

**Comment by shu-mutou** [comment]
Kubernetes Dashboard 2.0.0 will be officially released by the end of March, please be patient. Thanks!

**Comment by shu-mutou** [comment]
Also, you can use image that includes latest commit on master branch from following:
https://hub.docker.com/u/kubernetesdashboarddev

**Comment by atoato88** [comment]
/retitle Add support for dashboard v2.0.0 on dashboard-operator

**Comment by atoato88** [comment]
@johnsonj
I've rabsed the code and retitled this PR (remove [WIP] and change PR description).
Could you recheck?

**Comment by johnsonj** [comment]
Thanks @atoato88 !

/lgtm
/approved

**Pull request merged**
