### PR TITLE
Fix metrics reconcilation

### PR DESCRIPTION
**Pull request by rajansandeep**
Fixes panic when enabling metrics on an operator.

### CODE REVIEW

**Comment by atoato88** [comment]
/lgtm

Thank you to update!
And I'll check #125 also.

**Comment by atoato88** [comment]
/assign @justinsb 
Could you review this and other related PRs(#122, #125) ?

**Comment by justinsb** [comment]
Thanks - nice fix & I like the cleanup also!

/approve
/lgtm

**Comment by atoato88** [comment]
Thank you to review & approve! :smile:

**Pull request merged**
