### PR TITLE
Various docs fixes

### PR DESCRIPTION
**Pull request by prachirp**
Fixes typos, broken links, grammar and capitalization.

### CODE REVIEW

**Comment by justinsb** [comment]
Thanks @prachirp  - test failures are unrelated and I'll fix.

I suspect this won't merge until I've addressed the test deprecation, but ...

/approve
/lgtm

**Comment by justinsb** [comment]
(Fix for the tests should be in #134)

**Review by rajansandeep — APPROVED** [review]
/lgtm

**Pull request merged**
