### PR TITLE
Add support for hooks to the reconciler

### PR DESCRIPTION
**Pull request by justinsb**
Hooks are an extension of the sink concept that we already use for
watches, but support more interception points and we can have multiple
hooks.

### CODE REVIEW

**Review by atoato88 — COMMENTED** [review]
Almost LGTM, just one thing.
Please check the comment.

**Comment by atoato88** [comment]
@justinsb 
Is this PR still live?
This PR needs rebase, could you do that?

**Review by yuwenma — APPROVED** [review]

**Comment by yuwenma** [comment]
/LGTM

Everything looks good except the CI test failure.

**Comment by justinsb** [comment]
> Is this PR still live?

Yes, sorry, I've just been stuck trying to figure out how to get all these tests all working again.  The testing became so strict that it because impossible to merge code.

That said, I think I've got it now... we need to normalize APIResources (#312), we need to normalize discovery requests because kubectl doesn't do them in any predictable order (#313), and then we need to update everything (#307), and then finally I will change this PR to set up the watches in BeforeApply instead of AfterApply (which is actually really easy with this PR).

And then I think we're back in business :-)

**Pull request merged**
