### PR TITLE
Play nicely with third-party testing libraries

### PR DESCRIPTION
**Pull request by tomasaschan**
**What this PR does / why we need it**:

This makes the validator use an `interface` compatible with `*testing.T` instead of using `*testing.T` directly, in order to allow third-party testing libraries to provide an equivalent implementation instead of the built-in one.

See e.g. https://onsi.github.io/ginkgo/#using-third-party-libraries for a use case of this setup.

### CODE REVIEW

**Comment by tomasaschan** [comment]
Ping @justinsb :)

**Comment by atoato88** [comment]
/lgtm
It looks good, and pased the test.

**Comment by tomasaschan** [comment]
Ping! Could someone please /approve this? Would be nice to get it into `master` so we can use this in our operator test suites.

**Pull request merged**
