### PR TITLE
Cherry pick of #212: Introduce setters for name and namespace

### PR DESCRIPTION
**Pull request by justinsb**
Cherry pick of #212 on release-0.11

#212:Introduce setters for name and namespace

Edited to remove release notes for future release and to continue to expose underlying variables (for compatability).

### CODE REVIEW

**Comment by justinsb** [comment]
/assign @barney-s 

I think if we're going to maintain older branches (which I think we can/should), then we need PRs like this which avoid _too_ much reworking of other cherry picks.

Also I have a nice (IMO) script/tool that I'm working on for these that I can share with you :-)

**Review by yuwenma — APPROVED** [review]

**Comment by yuwenma** [comment]
As kubebuilder-declarative-pattern usres, I'm looking forward to these Setter methods.

**Comment by justinsb** [comment]
Thanks @yuwenma - you should be able to say `/lgtm` for the robots to auto-merge the PR

**Pull request merged**
